name: Setup Snaps
description: |
  Download and install one or more snaps from the snap store, with caching.

inputs:
  snaps:
    description: |
      A multi-line string of snaps to install. The format is as follows:

        snap-name [ --channel=channel ]

runs:
  using: composite
  steps:
    - name: Check OS and install snap if necessary
      shell: bash
      run: |
        if [[ '${{ runner.os }}' != 'Linux' ]]; then
          echo -e "\e[31mERROR\e[0m: This action only works on Linux runners" >> /dev/stderr
          echo "# Tried to get snaps on non-Linux runner" >> "${GITHUB_STEP_SUMMARY}"
          exit 1
        fi

        if ! command -v snap || ! command -v jq; then
          if command -v apt-get; then
            if ! sudo apt-get --yes install snapd xdelta3 jq; then
              sudo apt-get update
              sudo apt-get --yes install snapd xdelta3 jq
            fi
          else
            echo -e "\e[31mERROR\e[0m: needed command unavailable and unknown Linux distribution" >> /dev/stderr
          fi
        fi
        sudo snap refresh --hold=48h
    - name: Get cached snaps
      uses: actions/cache/restore@v4
      id: restore
      with:
        path: ${{ runner.temp }}/.snap_cache
        key: snap-cache-${{ runner.arch }}-${{ github.workflow }}-${{ github.job }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          snap-cache-${{ runner.arch }}-${{ github.workflow }}-${{ github.job }}-${{ github.ref }}-
          snap-cache-${{ runner.arch }}-${{ github.workflow }}-${{ github.job }}-
          snap-cache-${{ runner.arch }}-${{ github.workflow }}-
          snap-cache-${{ runner.arch }}-
    - name: Setup snaps
      shell: bash
      run: |
        mapfile snaps -t <<EOF
        ${{ inputs.snaps }}EOF

        mkdir -p "${{ runner.temp }}/.snap_cache"
        cd "${{ runner.temp }}/.snap_cache"

        mkdir old_snaps
        mv *.snap *.assert old_snaps || true

        source ${{ github.action_path }}/helpers.sh

        if [[ -f cached.assert ]]; then
          sudo snap ack cached.assert
          find . -name '*.assert' -exec snap ack '{}' ';'
          sudo snap install --ignore-validation *.snap
        fi

        for snap_line in "${snaps[@]}"; do
          cache_snap $snap_line &
        done

        wait

        rm -rf old_snaps

        sudo cp --no-clobber /var/lib/snapd/snaps/*.snap "${{ runner.temp }}/.snap_cache" || true
        sudo rm -f snapd*.snap  # Don't update snapd
        sudo chown "${USER}" "${{ runner.temp }}/.snap_cache"/*.snap || true
        sudo chmod a+r "${{ runner.temp }}/.snap_cache"/*.snap || true
        # Get all assertions
        find /var/lib/snapd/assertions -type f -exec cat '{}' ';' -printf '\n'  > "${{ runner.temp }}/.snap_cache/cached.assert"

        wait
    - name: Save cached snaps
      uses: actions/cache/save@v4
      with:
        path: ${{ runner.temp }}/.snap_cache
        key: ${{ steps.restore.outputs.cache-primary-key }}
